# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_date', models.DateTimeField(verbose_name='Время урока')),
                ('lesson_status', models.CharField(choices=[('DONE', 'Урок проведен'), ('CANCELED', 'Урок отменен'), ('MOVED', 'Урок перенесен')], default='DONE', max_length=8, verbose_name='Статус урока')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Доп.информация')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.ClassRoom', verbose_name='Кабинет')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.SchoolClass', verbose_name='Класс')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.Subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.Teacher', verbose_name='Учитель')),
            ],
            options={
                'permissions': (('add_schedule_entity', 'Добавление уроков'), ('edit_schedule_entity', 'Редактирование уроков'), ('delete_schedule_entity', 'Удаление уроков')),
                'verbose_name_plural': 'Расписание уроков',
                'db_table': 'schedule_lessons',
                'verbose_name': 'Расписание уроков',
            },
        ),
        migrations.CreateModel(
            name='LessonTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_time', models.TimeField(verbose_name='Время начала урока')),
                ('end_time', models.TimeField(verbose_name='Время окончания урока')),
                ('rest_time', models.TimeField(verbose_name='Перерыв после урока')),
            ],
            options={
                'verbose_name_plural': 'Расписание звонков',
                'db_table': 'catalogs_lesson_time',
                'default_permissions': (),
                'permissions': (('add_lesson_time_entity', 'Добавление расписания звонков'), ('update_lesson_time_entity', 'Редактирование расписания звонков'), ('delete_lesson_time_entity', 'Удаление расписания звонков')),
                'verbose_name': 'Расписание звонков',
                'ordering': ('begin_time',),
            },
        ),
        migrations.CreateModel(
            name='SchoolQuarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter_number', models.CharField(choices=[('1', 'Первая'), ('2', 'Вторая'), ('3', 'Третья'), ('4', 'Четвертая')], max_length=1, verbose_name='Учебная четверть')),
                ('start_date', models.DateField(verbose_name='Начало учебной четверти')),
                ('end_date', models.DateField(verbose_name='Конец учебной четверти')),
            ],
            options={
                'permissions': (('add_school_quarter_entity', 'Добавление учебной четверти'), ('update_school_quarter_entity', 'Редактирование учебной четверти'), ('delete_school_quarter_entity', 'Удаление учебной четверти')),
                'verbose_name_plural': 'Учебные четверти',
                'db_table': 'schedule_school_quarter',
                'verbose_name': 'Учебная четверть',
            },
        ),
        migrations.CreateModel(
            name='WorkPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_period', models.CharField(choices=[('EVERY_WEEK', 'Каждая неделя'), ('EVEN_WEEK', 'Первая неделя'), ('ODD_WEEK', 'Вторая неделя')], max_length=10, verbose_name='Учебная неделя')),
                ('week_lesson_count', models.IntegerField(verbose_name='Уроков в неделю')),
                ('total_lesson_count', models.IntegerField(verbose_name='Всего уроков')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_plan', to='catalogs.SchoolClass', verbose_name='Класс')),
                ('school_quarter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_plan', to='schedule.SchoolQuarter', verbose_name='Четверть')),
                ('sub_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.SchoolClassGroup', verbose_name='Подгруппа')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_plan', to='catalogs.Subject', verbose_name='Учебный предмет')),
            ],
            options={
                'permissions': (('add_work_plan_entity', 'Добавление учебного плана'), ('update_work_plan_entity', 'Редактирование учебного плана'), ('delete_work_plan_entity', 'Удаление учебного плана')),
                'verbose_name_plural': 'Учебные планы',
                'db_table': 'schedule_work_plan',
                'verbose_name': 'Учебный план',
            },
        ),
    ]
