# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 12:12
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(db_index=True, default=datetime.datetime(2017, 9, 30, 12, 12, 13, 442561), verbose_name='Начало работы')),
                ('end_time', models.DateTimeField(db_index=True, null=True, verbose_name='Конец работы')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_times', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'default_permissions': (),
                'verbose_name': 'Рабочее время',
                'db_table': 'work_time',
                'permissions': (('add_work_time', 'Добавление рабочего времени'), ('change_work_time', 'Обновление рабочего времени'), ('delete_work_time', 'Удаление рабочего времени')),
                'verbose_name_plural': 'Рабочее время',
            },
        ),
    ]
