# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=40, verbose_name='ФИО')),
            ],
            options={
                'permissions': (('add_author', 'Добавление автора'), ('change_author', 'Обновление информации автора'), ('delete_author', 'Удаление автора')),
                'verbose_name_plural': 'Авторы',
                'default_permissions': (),
                'verbose_name': 'Автор',
                'db_table': 'quotes_author',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Название')),
            ],
            options={
                'permissions': (('add_category', 'Добавление категории'), ('change_category', 'Обновление информации категории'), ('delete_category', 'Удаление категории')),
                'verbose_name_plural': 'Категории',
                'default_permissions': (),
                'verbose_name': 'Категория',
                'db_table': 'quotes_category',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Цитата')),
                ('source', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ресурс')),
                ('year', models.CharField(blank=True, max_length=20, null=True, verbose_name='Год')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', related_query_name='quote', to='quotes.Author', verbose_name='Автор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', related_query_name='quote', to='quotes.Category', verbose_name='Категория')),
            ],
            options={
                'permissions': (('add_quote', 'Добавление цитаты'), ('change_quote', 'Обновление информации цитаты'), ('delete_quote', 'Удаление цитаты')),
                'verbose_name_plural': 'Цитаты',
                'default_permissions': (),
                'verbose_name': 'Цитата',
                'db_table': 'quotes_quote',
            },
        ),
    ]
