# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 12:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ext_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extuser',
            name='register_date',
            field=models.DateField(default=datetime.datetime(2017, 9, 30, 12, 7, 50, 59470), verbose_name='Дата регистрации'),
        ),
    ]
